# permissions for end users to view routerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routerconfig-viewer-role
rules:
- apiGroups:
  - group.test.org
  resources:
  - routerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - group.test.org
  resources:
  - routerconfigs/status
  verbs:
  - get
