# permissions for end users to edit routerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routerconfig-editor-role
rules:
- apiGroups:
  - group.test.org
  resources:
  - routerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - group.test.org
  resources:
  - routerconfigs/status
  verbs:
  - get
